bugTracker/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace bugTracker.Models
{
    public class Project
    {
        //Primary Key
        public int Id { get; set; }

        //Properties
        [Required]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Details { get; set; }

        public DateTimeOffset Created { get; set; }

        //Foreign Keys

        //Navigation - To Children
        public virtual ICollection<Ticket> Tickets { get; set; }

        //Virtual Nav for the many to many table with ApplicationUser
        public virtual ICollection<ApplicationUser> Users { get; set; }

        public Project()
        {
            Tickets = new HashSet<Ticket>();
            Users = new HashSet<ApplicationUser>();
        }
    }
}

bugTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bugTracker.Models;
using bugTracker.Helpers;
using Microsoft.AspNet.Identity;

namespace bugTracker.Controllers
{
    [RequireHttps]
    [Authorize]
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserRolesHelper userHelper = new UserRolesHelper();
        private ProjectsHelper projectHelper = new ProjectsHelper();

        // GET: Projects
        
        public ActionResult Index()
        {
            var projects = projectHelper.ListUserProjects(User.Identity.GetUserId()).ToList();
            ViewBag.Projects = string.Empty.ToList();

            if (User.IsInRole("Developer") || User.IsInRole("Submitter"))
            {
                return View(projects);
            }

            ViewBag.Projects = db.Projects.ToList();

            return View(projects);
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Details,Created")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.Created = DateTimeOffset.Now;

                db.Projects.Add(project);
                db.SaveChanges();

                projectHelper.AddUserToProject(User.Identity.GetUserId(), project.Id);

                return RedirectToAction("Create");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Edit(int id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            Project project = db.Projects.Find(id);

            if (project == null)
            {
                return HttpNotFound();
            }

            if (!(projectHelper.IsUserOnProject(User.Identity.GetUserId(), project.Id) && User.IsInRole("Project Manager")) && !(User.IsInRole("Administrator")))
            {
                return HttpNotFound();
            }

            ViewBag.UserOn = new MultiSelectList(projectHelper.UsersInProjNotInRole(id, "Project Manager"), "Id", "UserName");
            ViewBag.UserOff = new MultiSelectList(projectHelper.UsersNotOnProjOrInRole(id, "Project Manager"), "Id", "UserName");

            foreach (var pm in userHelper.UsersInRole("Project Manager"))
            {
                if(projectHelper.IsUserOnProject(pm.Id, id))
                {
                    ViewBag.CurrentPm = pm.UserName;
                }
            }

            ViewBag.PMs = new SelectList(userHelper.UsersInRole("Project manager"), "Id", "UserName");

            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Details,Created")] Project project, List<string> UserOff, List<string> UserOn, string PMs)
        {
            if (ModelState.IsValid)
            {
                if (!(UserOff is null))
                {
                    foreach (var user in UserOff)
                    {
                        projectHelper.AddUserToProject(user, project.Id);
                    }
                }

                if (!(UserOn is null))
                {
                    foreach (var user in UserOn)
                    {
                        projectHelper.RemoveUserFromProject(user, project.Id);
                    }
                }

                if (!(string.IsNullOrEmpty(PMs)))
                {
                    if(!(projectHelper.IsUserOnProject(PMs, project.Id)))
                    {
                        projectHelper.AddUserToProject(PMs, project.Id);
                    }
                }

                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Project project = db.Projects.Find(id);

            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //TODO: Remove all users from project

            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bugTracker/Views/Projects/Create.cshtml
@model bugTracker.Models.Project

@{
    ViewBag.Title = "Create";
}


<div class="col-md-12 col-sm-12 col-xs-12">
<div class="x_panel">
    <div class="x_title">
        <h2>Create Project <small>“A project without a critical path is like a ship without a rudder.” ~ D. Meyer</small></h2>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <br />
        @using (Html.BeginForm("Create", "Projects", FormMethod.Post, new { @class = "form-horizontal form-label-left", id = "createFrm" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.TextAreaFor(model => model.Details, 4, 20, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }
        <div class="ln_solid"></div>
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <input type="button" id="createBtn" class="btn btn-success" value="Submit" />
            @Html.ActionLink("Cancel", "Index", "Projects", null, new { @class="btn btn-warning" })
        </div>


    </div>
</div>
    </div>

@section Scripts {
<script>
    $("#createBtn").click(function () {
        $("#createFrm").submit();
    });
</script>

    @Scripts.Render("~/bundles/jqueryval")
}

bugTracker/Views/Projects/Delete.cshtml
@model bugTracker.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

bugTracker/Views/Projects/Details.cshtml
@model bugTracker.Models.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

bugTracker/Views/Projects/Edit.cshtml
@using bugTracker.Helpers
@model bugTracker.Models.Project

@{
    var projectHelper = new ProjectsHelper();
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Projects", FormMethod.Post, new { @id = "editProjectForm" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Created)

<div class="form-horizontal">
    <div class="container">
        <div class="x_panel">
            <div class="x_title">
                <h2>Edit Project</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-1" })
                        <div class="col-md-11">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-1" })
                        <div class="col-md-11">
                            @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Assign New Users From List <small>No selection will leave current users unassigned</small></h2>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <div class="">
                                        @*<ul class="to_do">
                                @foreach (var user in ViewBag.Users)
                                {
                                    <li>
                                        @if (projectHelper.IsUserOnProject(user.Value, Model.Id))
                                        {
                                            @Html.CheckBox("userId", true, new { @id = $"{user.Id}", @value =$"{user.Id}", @class = "flat" })
                                            @Html.Label($"{user.LastName}, {user.FirstName}")
                                        }
                                        else
                                        {
                                            @Html.CheckBox("userId", false, new {@id=$"{user.Id}", @value = $"{user.Id}", @class = "flat" })
                                            @Html.Label($"{user.LastName}, {user.FirstName}")
                                        }

                                    </li>
                                }
                            </ul>*@
                                        @if (ViewBag.UserOff.Items.Count == 0)
                                        {
                                            <div class="text-center">No Users to display</div>
                                        }
                                        else
                                        {
                                            @Html.ListBox("UserOff", null, new { @class = "customListBox" })
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Remove Users From List <small>No selection will leave current users assigned</small></h2>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <div class="">
                                        @if (ViewBag.UserOn.Items.Count == 0)
                                        {
                                            <div class="text-center">No Users to display</div>
                                        }
                                        else
                                        {
                                            @Html.ListBox("UserOn", null, new { @class = "customListBox" })
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Assign New Project Manager <small>No selection will leave current project manager assigned</small></h2>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <div class="">
                                        @if (!(ViewBag.CurrentPm is null))
                                        {
                                            <div class="row">The Current PM for this project is: @ViewBag.CurrentPm</div>
                                        }
                                        <div class="row">
                                            @Html.DropDownList("PMs", null, "-- Select a PM --", htmlAttributes: new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-offset-1 col-md-11">
                            <input id="editPrjBtn" type="button" value="Save" class="btn btn-default btn-success" />
                        </div>
                    </div>
                </div>
                </div>
        </div>
    </div>
</div>
}


@section scripts
{
    <script>
        $("#editPrjBtn").click(function () {
            $("#editProjectForm").submit();
        });

        $(function () {
            var length = parseInt($(".customListBox option").length);
            $(".customListBox").attr("size", length > 10 ? length : 10);
        });
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

bugTracker/Views/Projects/Index.cshtml
@model IEnumerable<bugTracker.Models.Project>
@using bugTracker.Models
@using bugTracker.Extensions
@using bugTracker.Helpers
@using Microsoft.AspNet.Identity

@{
    ProjectsHelper projectsHelper = new ProjectsHelper();
    ViewBag.Title = "Projects";
}

<div class="container">
    <div class="row">
        <div class="x_panel">
            <div class="x_title">
                <h2>My @ViewBag.Title</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="allPrjTable" class="table table-striped projects">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Details)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Created)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Details)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Created)
                                </td>

                                @if (User.IsInRole("Administrator") || User.IsInRole("Project Manager"))
                                {
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })

                                        @*<a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                            <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                            <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>*@
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @if (ViewBag.Projects.Count > 0)
    {
        <div class="row">
            <div class="x_panel">
                <div class="x_title">
                    <h2>All Projects</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="prjTable" class="table table-striped projects">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Details)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Created)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Project item in (List<Project>)ViewBag.Projects)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Details)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Created)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
</div>

<!-- Esecute Datatables <thead><tbody> -->
@section scripts {
    <script>
        $(document).ready(function () {
            $('#prjTable').DataTable();
        });

        $(document).ready(function () {
            $('#allPrjTable').DataTable();
        });
    </script>
}